#server.servlet.context-path=/eBusiness
#spring.datasource.url=jdbc:mysql://localhost:3306/shop?characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#logging.level.com.ch.ebusiness.repository=debug
#spring.thymeleaf.cache=false
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=500MB
#
#server.port=555
#
#mybatis-plus.global-config.db-config.table-prefix=tbl_
#
#
#contec
server:
  servlet:
    context-path: /eBusiness
  port: 555
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  redis:
    jedis:
      pool:
        max-wait: 1ms
    host: localhost

mybatis-plus:
  type-aliases-package: com.ch.ebusiness.entity
  mapper-locations: classpath:mappers/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  level:
    com.ch.ebussiness: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

mybatis:
  type-aliases-package: com.ch.ebusiness.entity
  mapper-locations: mappers/*.xml




#mybatis.type-aliases-package=com.ch.ebusiness.entity
#mybatis.mapperLocations=classpath:mappers/*.xml
